name: Build KernelSU
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm8550'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus_12r_v'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'kalama'

jobs:
  build:
   runs-on: self-hosted

   steps:
     - name: Check Out
       uses: actions/checkout@v3
       
     - name: Cleanup
       uses: rokibhasansagar/slimhub_actions@main

     - name: Configure Git
       run: |
        git config --global user.name "thomas"
        git config --global user.email "thomas@alpenglow.com.cn"

     - name: Clean up disk space
       run: |
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet /etc/mysql /var/lib/mysql
        sudo rm -rf /usr/local/lib/android
        df -h
        
     - name: Install dependencies
       run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y python3 git curl

     - name: Install repo tool
       run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo

     - name: Initialize repo and sync
       run: |
        mkdir kernel_workspace && cd kernel_workspace
        repo init -u https://github.com/ubuntu2029/kernel_manifest.git -b refs/heads/oneplus/${{ github.event.inputs.CPU }} -m ${{ github.event.inputs.FEIL }}.xml --depth=1
        repo sync
        rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
        rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
        sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion
        sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion
        cd kernel_platform && cat common/arch/arm64/configs/gki_defconfig > msm-kernel/common/arch/arm64/configs/gki_defconfig

     - name: Set up KernelSU
       run: |
        cd kernel_workspace/kernel_platform
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
      
     - name: Build kernel
       run: |
        cd kernel_workspace
        # export LTO=thin
        ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ github.event.inputs.CPUD }} gki

     - name: Make AnyKernel3
       run: |
        git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
        rm -rf ./AnyKernel3/.git
        cp kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-gki/dist/Image ./AnyKernel3/

     - name: Upload AnyKernel3
       uses: actions/upload-artifact@v4
       with:
        name: AnyKernel3_KernelSU_Next_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
        path: ./AnyKernel3/*

     
